apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shipment.name" . }}
  labels:
    {{- include "shipment.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "34%"
      maxSurge: 0
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "shipment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shipment.selectorLabels" . | nindent 8 }}
      annotations:
        ofload.io/commit: "{{ $.Values.commit }}"
        ofload.io/app: "deployment-{{ include "shipment.name" . }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            {{- include "shipment.app.variables" . | nindent 12 }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.app.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.app.service.port }}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts: []
        - name: "nginx"
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.service.port }}
            - name: https
              containerPort: 443
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.nginx.service.port }}
            initialDelaySeconds: 20
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.nginx.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 5
          volumeMounts: []
      volumes: []
