apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shipment.name" . }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:114211595136:certificate/f2698a12-6043-4400-a39e-d68fb3dbbe86, arn:aws:acm:ap-southeast-1:114211595136:certificate/c653f871-15c7-473e-8ab3-095718c27e6b, arn:aws:acm:ap-southeast-1:114211595136:certificate/02795ee9-d5e5-4711-92d4-9273a0b7b904
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
spec:
  ingressClassName: alb
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "shipment.name" . }}
                port:
                  number: 80
