apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shipment.name" . }}
  labels:
    app: {{ include "shipment.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  aws-key: {{ .Values.vars.aws.key | b64enc }}
  aws-secret: {{ .Values.vars.aws.secret | b64enc }}
  newrelic-key: {{ .Values.vars.newrelic.key | b64enc }}
  postgres-db-password: {{ .Values.vars.postgres.db.password | b64enc }}
