apiVersion: v1
kind: Service
metadata:
  name: {{ include "shipment.name" . }}
  labels:
    {{- include "shipment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ include "shipment.name" . }}
      port: {{ .Values.service.http.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.http.internalPort }}
  selector:
    {{- include "shipment.selectorLabels" . | nindent 4 }}
