replicaCount: 2

commit: ""

app:
  image:
    repository: 114211595136.dkr.ecr.ap-southeast-1.amazonaws.com/shipment-app
    pullPolicy: Always
    tag: ""
  resources:
    limits:
      memory: 256Mi
      cpu: "250m"
    requests:
      memory: 128Mi
      cpu: "100m"
  service:
    port: 9000


nginx:
  image:
    repository: 114211595136.dkr.ecr.ap-southeast-1.amazonaws.com/shipment-nginx
    pullPolicy: Always
    tag: ""
  resources:
    limits:
      memory: 256Mi
      cpu: "250m"
    requests:
      memory: 128Mi
      cpu: "80m"
  service:
    port: 80

service:
  type: NodePort
  http:
    externalPort: 80
    internalPort: 80


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

domain: ""

env:
  vars:
    appEnv: "dev"
    postgresDbHost: "dev-db.cczxoqsp5qxa.ap-southeast-1.rds.amazonaws.com"
    postgresDbUser: "postgres"
    postgresDbPort: "5432"
    postgresDbName: "shipment"

