replicaCount: 1
domain: "dev-shipment.ofload.net"

nginx:
  resources:
    limits:
      memory: 64Mi
      cpu: "50m"
    requests:
      memory: 64Mi
      cpu: "20m"

app:
  resources:
    limits:
      memory: 128Mi
      cpu: "50m"
    requests:
      memory: 64Mi
      cpu: "20m"

autoscaling:
  enabled: false
