name: Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cancel_previous:
    name: Cancel any still running workflows on this branch
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: shivammathur/setup-php@2.25.1

      - name: Copy .env
        uses: canastro/copy-file-action@master
        with:
          source: ".env.dist"
          target: ".env"

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Build
        run: make down && make up

      - name: Run Migrations
        run: make migration-up

      - name: Ide-helper generate
        run: docker compose run --rm php composer ide-helper

      - name: Run PHPChecks
        run: make validations

      - name: Run Tests
        run: make tests-coverage-txt
