name: Rollback

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment"
        options:
          - dev
          - prod

jobs:
  rollback:
    name: "Rollback"
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Configure K8S access
        id: k8s-access
        run: |
          aws eks update-kubeconfig --region ${{secrets.AWS_REGION}} --name ${{vars.K8S_CLUSTER}}

      - name: Helm Version
        run: helm version

      - name: Rollback
        run: helm rollback shipment 0 -n shipment
